team_communication: automatically detect target ip address
bit-bots/bitbots_meta pull request #589
Opened 2024-07-20 08:29 UTC by timonegk

# Summary
Automatically detect the target address for team communication from the wifi interface using `netifaces`.
In case of any problem, the default address configured is used.

## Related issues
Closes #578.

## Checklist

- [ ] Run `colcon build`
- [ ] Write documentation
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Create issues for future work
- [ ] Triage this PR and label it

2024-07-20 09:43 UTC, texhnolyze requested changes

2024-07-20 09:43 UTC, texhnolyze commented on bitbots_team_communication/bitbots_team_communication/bitbots_team_communication/communication.py
>          if self.target_ip.is_loopback:
Since you removed `local_target_ports` this whole block should also be removed

2024-07-26 12:05 UTC, jaagut requested changes

2024-07-26 12:05 UTC, jaagut commented on bitbots_team_communication/bitbots_team_communication/bitbots_team_communication/communication.py
> +        if self.target_ip is None:
`self.target_ip` may not exist at this point

2024-07-26 12:05 UTC, jaagut commented on bitbots_team_communication/bitbots_team_communication/config/team_communication_config.yaml
> +    # Fallback, only used if detect_target_ip is false. This should be the highest IP in the subnet e.g. 172.20.255.255
`only used if detect_target_ip is false` this is false or irritating.

Its used:
- _if detect_target_ip is false_
- _if detect_target_ip is true, but auto-detection failed_

2024-09-25 22:48 UTC, Flova commented
What's the state with this PR? @timonegk

2024-09-26 07:21 UTC, timonegk commented
It is still relevant but the reviews must be addressed and it has to be tested

2026-06-01 16:44 UTC, closed without merging