fix install script
bit-bots/bitbots_meta pull request #82
Opened 2020-12-03 17:38 UTC by timonegk

## Proposed changes
Fixes install script. Not tested yet.

## Related issues
Closes #73.

## Necessary checks
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2021-01-28 14:48 UTC, timonegk commented
I tested the script in a fresh docker container and it works.

2021-01-29 09:11 UTC, ftsell requested changes

2021-01-29 09:11 UTC, ftsell commented on scripts/install.pl
> +    or system "sudo pip3 install git+https://github.com/catkin/catkin_tools.git"
Why as root? Is `pip3 install --user` not more appropriate?

2021-01-29 09:11 UTC, ftsell commented on scripts/install.pl
> +    print "Do you want to clone the private repos ('ansible_robots', 'doku' and 'basler_drivers') now?$/";
It is now only called `ansible`

2021-01-29 09:11 UTC, ftsell commented on scripts/install.pl
> +        system 'git clone git@git.mafiasi.de:Bit-Bots/ansible.git'
I personally have ansible cloned into bitbots_tools because there it is registered in the .gitigignore file. We might want to do the same here too

2021-01-29 09:11 UTC, ftsell commented on scripts/install.pl
> +            system 'git clone git@git.mafiasi.de:Bit-Bots/doku.git'
I personally have the internal docs cloned into bitbots_tools as bitbots_docs_internal because it is registered in the .gitignore file there. We might want to do the same here too

2021-01-29 09:55 UTC, timonegk commented on scripts/install.pl
> +    or system "sudo pip3 install git+https://github.com/catkin/catkin_tools.git"
Maybe. But many (especially new) users don't have `~/.local/bin` in their `PATH`, so I figured it would be easier to just install it globally (and it doesn't interfere with system packages because `pip` installs to `/usr/local/`).

2021-01-29 11:06 UTC, ftsell commented on scripts/install.pl
> +    or system "sudo pip3 install git+https://github.com/catkin/catkin_tools.git"
hmm, alright

2021-01-29 11:07 UTC, ftsell submitted a review, later dismissed

2021-02-06 10:21 UTC, timonegk commented
I added a cleanup of the `scripts` folder and the `Makefile`. I removed the `make build` because I never heard that anybody used it and removed the scripts `build.sh` (for the same reason), `create_venv.bash` (also unused), `install_py_extension.bash` (is now done via cmake) and `repair.sh` (fortunately not needed anymore).

2021-02-07 15:27 UTC, ftsell approved these changes

2021-02-07 15:29 UTC, merged